version: '3.8'

services:
  learnjenkins:
    container_name: learnjenkinsapi_dev
    image: learnjenkinsapi-dev:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7002
    ports:
      - "7003:8080" 
    volumes:
      - .:/app
    restart: always
