version: '3.8'

services:
  learnjenkinsapi:
    container_name: learnjenkinsapi_prod
    image: learnjenkinsapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7002
    ports:
      - "7002:8080"
    restart: always
